#!/bin/bash
#Version: 1.0
#Date: August, 8, 2016
#Author: Laith Al Obaidy,laith@laith.info

################################################################################
echo 'Enter the domain name:'
read DOMAIN


#Checking Apache group, Debian based or RHEL.
if [ -f /etc/redhat-release ]; then
	GROUP=apache
   else
	GROUP=www-data
fi
##
if [ -d /var/www/vhosts/$DOMAIN ]; then
echo "Your domain $DOMAIN is exist!!"

groupadd sftponly #exec 2>/dev/null 
useradd -s /sbin/nologin $DOMAIN #exec 2>/dev/null
usermod -G$GROUP,sftponly $DOMAIN
mkdir -p /home/$DOMAIN/$DOMAIN
chown root:root /home/$DOMAIN
chmod 755 /home/$DOMAIN
echo "/var/www/vhosts/$DOMAIN /home/$DOMAIN/$DOMAIN none rw,bind,nobootwait 0 0" >> /etc/fstab
mount /home/$DOMAIN/$DOMAIN
echo "$DOMAIN:$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)" >> /tmp/passwords.txt
cat /tmp/passwords.txt | chpasswd

echo "  "
echo "Your domain $DOMAIN has been jailed into /home/$DOMAIN"
echo "Your domain user password is `cat /tmp/passwords.txt`"
echo " "
rm -rf /tmp/passwords.txt

else
echo "Your domain $DOMAIN does not exist in /var/www/vhosts"
fi

#EOT
